language: ruby
rvm: 3.4.2
dist: noble
env:
  global:
    - RAILS_ENV=test
    - PG_HOST=localhost
    - PGUSER=postgres
    - PGHOST=127.0.0.1
    - PSQL_PAGER=""
    - NODE_ENV=production
    - NODE_OPTIONS=--max-old-space-size=6000

services:
  - postgresql
  - mongodb
  - rabbitmq

before_install:
  - sudo apt-get -y install elasticsearch
  - 'sudo sed -i "s/enabled: true/enabled: false/g" /etc/elasticsearch/elasticsearch.yml'
  - sudo systemctl start elasticsearch
  - until curl --silent -XGET --fail http://localhost:9200; do printf '...\n'; sleep 2; done
install: skip
script: true
